import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { keyholdersMail } from '../src/lib/data/keyholders-mail.ts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CHECK = process.argv.includes('--check');
const REPO_URL = 'https://github.com/Great-Falls-Tool-Bus/greatfallstoolbus.org';
const GENERATED =
	'<!-- GENERATED by scripts/render-keyholders-mail-surfaces.mts from src/lib/data/keyholders-mail.ts. Do not edit by hand. -->';

type SkillMeta = {
	name: string;
	description: string;
};

function bullet(items: readonly string[]): string {
	return items.map((item) => `- ${item}`).join('\n');
}

function numbered(items: readonly string[]): string {
	return items.map((item, index) => `${index + 1}. ${item}`).join('\n');
}

function shortDescription(description: string): string {
	const normalized = description
		.replace(/\bCLAUDE\.md\b/g, 'provider compatibility shims')
		.replace(/\btinyland-inc\/site\.scaffold\b/g, 'the Tinyland scaffold contract')
		.replace(/\bsite\.scaffold\b/g, 'the Tinyland scaffold')
		.replace(/\bsite-scaffold\b/g, 'scaffold-core')
		.replace(/\s+/g, ' ')
		.trim();
	return normalized.length > 220 ? `${normalized.slice(0, 217)}...` : normalized;
}

function parseFrontmatter(raw: string): SkillMeta | null {
	const match = raw.match(/^---\n([\s\S]*?)\n---\n/);
	if (!match) return null;
	const fields = new Map<string, string>();
	let current: string | null = null;
	const buffer: string[] = [];
	for (const line of match[1].split('\n')) {
		const field = line.match(/^([a-z][a-z0-9_-]*):\s*(.*)$/);
		if (field) {
			if (current) fields.set(current, buffer.join('\n').trim());
			current = field[1];
			buffer.length = 0;
			if (field[2]) buffer.push(field[2]);
			continue;
		}
		if (current) buffer.push(line.trim());
	}
	if (current) fields.set(current, buffer.join('\n').trim());
	const name = fields.get('name');
	const description = fields.get('description');
	return name && description ? { name, description } : null;
}

async function loadSkills(): Promise<SkillMeta[]> {
	const skillsDir = join(ROOT, '.agents', 'skills');
	const entries = await readdir(skillsDir, { withFileTypes: true });
	const skills: SkillMeta[] = [];
	for (const entry of entries) {
		if (!entry.isDirectory()) continue;
		const raw = await readFile(join(skillsDir, entry.name, 'SKILL.md'), 'utf8');
		const meta = parseFrontmatter(raw);
		if (meta) skills.push(meta);
	}
	return skills.sort((a, b) => a.name.localeCompare(b.name, 'en'));
}

async function writeGenerated(relativePath: string, content: string): Promise<void> {
	const path = join(ROOT, relativePath);
	const normalized = content.endsWith('\n') ? content : `${content}\n`;
	if (CHECK) {
		let existing = '';
		try {
			existing = await readFile(path, 'utf8');
		} catch {
			throw new Error(`${relativePath} is missing; run just agent-surfaces`);
		}
		if (existing !== normalized) {
			throw new Error(`${relativePath} is stale; run just agent-surfaces`);
		}
		return;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, normalized);
}

function renderRunbook(): string {
	const clientSections = keyholdersMail.clientSetups
		.map(
			(client) => `## ${client.name}

${client.overview}

${bullet(client.tips)}`,
		)
		.join('\n\n');
	const flows = keyholdersMail.memberFlows.map((flow) => `## ${flow.title}\n\n${numbered(flow.steps)}`).join('\n\n');
	return `${GENERATED}

# ${keyholdersMail.listAddress} client setup

> Current boundary: ${keyholdersMail.status.mailbox} ${keyholdersMail.status.list}
> ${keyholdersMail.status.archive} ${keyholdersMail.status.directSubmit}

This document is rendered from the same source as the public contact-page cards,
the GFTB mail setup skill, and the agent-facing indexes. Update
\`src/lib/data/keyholders-mail.ts\`, then run \`just agent-surfaces\`.

## How the list works

- The mailbox/list address is \`${keyholdersMail.addresses.post}\`.
- Subscribe by email at \`${keyholdersMail.addresses.join}\`.
- Unsubscribe by email at \`${keyholdersMail.addresses.leave}\`.
- Reach list owners at \`${keyholdersMail.addresses.owner}\`.
- The public archive is HyperKitty after the TIN-2380 list runtime is applied and smoke-tested.

${flows}

${clientSections}

## Owners and moderators

${bullet(keyholdersMail.ownerModeratorTips)}
`;
}

function renderSkill(): string {
	const clientNotes = keyholdersMail.clientSetups
		.map((client) => `## ${client.name}\n\n${client.overview}\n\n${bullet(client.tips)}`)
		.join('\n\n');
	return `---
name: gftb-keyholders-mail
description: Help a user or their agent set up Great Falls Tool Bus keyholders mail and the future Mailman/HyperKitty list in Apple Mail, Gmail, Thunderbird, Geary, KMail, or a generic client while preserving live-vs-pending boundaries.
---

# GFTB Keyholders Mail

${GENERATED}

Use this when a person asks how to reach, join, filter, reply to, moderate, or
troubleshoot the Great Falls Tool Bus keyholders mailbox or future Mailman list.

## Live Boundary

- ${keyholdersMail.status.mailbox}
- ${keyholdersMail.status.list}
- ${keyholdersMail.status.archive}
- ${keyholdersMail.status.directSubmit}

Do not claim the list, archive, or direct-submit endpoint is live until the
corresponding smoke evidence lands.

## Addresses

${keyholdersMail.addressCards.map((card) => `- ${card.label}: \`${card.address}\` - ${card.note}`).join('\n')}
- Leave the list: \`${keyholdersMail.addresses.leave}\`

## Basic Flow

${keyholdersMail.memberFlows.map((flow) => `### ${flow.title}\n\n${numbered(flow.steps)}`).join('\n\n')}

${clientNotes}

## Owners And Moderators

${bullet(keyholdersMail.ownerModeratorTips)}
`;
}

function renderLlms(skills: readonly SkillMeta[]): string {
	const skillLines = skills
		.map(
			(skill) =>
				`- [${skill.name}](${REPO_URL}/blob/main/.agents/skills/${skill.name}/SKILL.md): ${shortDescription(skill.description)}`,
		)
		.join('\n');
	return `${GENERATED}

# greatfallstoolbus.org

> Great Falls Tool Bus is a static Cloudflare Pages spoke for a shared tool
> library on wheels in Lewiston-Auburn, Maine. Start with AGENTS.md, then use
> the project skills for task-specific behavior.

## Canonical

- [Agent contract](${REPO_URL}/blob/main/AGENTS.md)
- [README](${REPO_URL}/blob/main/README.md)
- [Repo manifest](${REPO_URL}/blob/main/tinyland.repo.json)
- [Decision packet](${REPO_URL}/blob/main/docs/decisions/0001-gftb-mvp-decisions.md)
- [Gate-opening criteria](${REPO_URL}/blob/main/docs/decisions/0004-gate-opening-criteria.md)
- [Keyholders client setup](${REPO_URL}/blob/main/docs/runbooks/keyholders-client-setup.md)
- [Justfile](${REPO_URL}/blob/main/Justfile)

## Mail Boundary

- ${keyholdersMail.status.mailbox}
- ${keyholdersMail.status.list}
- ${keyholdersMail.status.archive}
- ${keyholdersMail.status.directSubmit}

## Skills

${skillLines}

## Agent Routes

- [Agent AX map](https://greatfallstoolbus.org/agent)
- [Machine route map](https://greatfallstoolbus.org/agent-map.md)
- [Sitemap](https://greatfallstoolbus.org/sitemap.xml)

## Operating Constraints

- Use \`just <recipe>\` for every repo operation.
- Run \`just agent-surfaces\` after changing keyholders mail data or skills.
- Run gitleaks through Justfile recipes.
- Keep static spokes static. The form endpoint, Mailman runtime, HyperKitty,
  Anubis, DNS, and cluster applies live in the org apply-plane overlay.
`;
}

function renderAgentMap(skills: readonly SkillMeta[]): string {
	const skillLines = skills
		.map((skill) => `- \`.agents/skills/${skill.name}/SKILL.md\` - ${shortDescription(skill.description)}`)
		.join('\n');
	const clientLines = keyholdersMail.clientSetups.map((client) => `- ${client.name}: ${client.cardSummary}`).join('\n');
	return `${GENERATED}

# greatfallstoolbus.org Agent Map

## Read Order

1. \`AGENTS.md\`
2. Provider-specific compatibility shims only when a local agent runtime needs
   them; they are not the normative contract.
3. \`tinyland.repo.json\` for machine-readable repo shape.
4. \`docs/decisions/0001-gftb-mvp-decisions.md\` for GFTB authority boundaries.
5. \`docs/decisions/0004-gate-opening-criteria.md\` before changing public gate posture.
6. The relevant \`.agents/skills/*/SKILL.md\`.
7. \`Justfile\`.

## Skills

${skillLines}

Provider-specific discovery shims may symlink to the canonical \`.agents/skills/*\`
directories. Edit canonical skill files only.

## Keyholders Mail

- Mailbox/list address: \`${keyholdersMail.addresses.post}\`
- Subscribe: \`${keyholdersMail.addresses.join}\`
- Unsubscribe: \`${keyholdersMail.addresses.leave}\`
- Owners: \`${keyholdersMail.addresses.owner}\`
- Status: ${keyholdersMail.status.mailbox} ${keyholdersMail.status.list}

### Client Notes

${clientLines}

## Core Recipes

- \`just setup\`
- \`just check\`
- \`just build\`
- \`just ci\`
- \`just agent-surfaces\`
- \`just agent-surfaces-check\`
- \`just skills-validate\`
- \`just secrets-scan-dir\`
- \`just secrets-scan\`
- \`just conformance\`

## Prohibited

- Runtime database or backend in this static spoke.
- Hidden source-of-truth edits to generated agent/mail surfaces.
- Hard-coded Bazel cache, executor, token, or header values.
- Applying DNS, Access, Mailman, HyperKitty, Anubis, or cluster changes from this repo.
`;
}

async function main(): Promise<void> {
	await writeGenerated('docs/runbooks/keyholders-client-setup.md', renderRunbook());
	await writeGenerated('.agents/skills/gftb-keyholders-mail/SKILL.md', renderSkill());
	const skills = await loadSkills();
	await writeGenerated('static/llms.txt', renderLlms(skills));
	await writeGenerated('static/agent-map.md', renderAgentMap(skills));
}

main().catch((error: unknown) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
